const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const script=fs.readFileSync('lineuparr.html','utf8').split('<script>')[1].split('</script>')[0];
new vm.Script(script);
assert.ok(script.includes("document.getElementById('category-review-panel').before(tmdbPanel)"));
assert.ok(!script.includes("document.querySelector('main').prepend(tmdbPanel)"));
const nodes=[]; const make=()=>{const n={dataset:{},append(){},prepend(){},before(){},setAttribute(){},removeAttribute(){},addEventListener(t,f){this[t]=f}};nodes.push(n);return n};
let state='not-configured', posts=0, gets=0, timers=0, drafts=0, failPost=false;
const context=vm.createContext({document:{createElement:make,querySelector:make,getElementById:make},clearTimeout(){},setTimeout(){timers++;},loadDraft:async()=>{drafts++;},api:async(path,opts)=>{if(opts){posts++;if(failPost)throw new Error('timezone problem');return {state:'current',message:'scanned'}}gets++;return {state,message:state==='not-configured'?'Add TMDB_TOKEN':state}}});
vm.runInContext(script.slice(script.indexOf('    const tmdbPanel ='),script.indexOf('    initCollapsibleSections();',script.indexOf('    const tmdbPanel ='))),context);
(async()=>{
 await context.loadTMDBCategoryState(); const button=nodes[3];
 assert.ok(nodes.some(n=>n.className==='panel-chevron' && n.textContent==='›'),'TMDB header must use the shared disclosure chevron');
 assert.equal(button.hidden,true); assert.equal(button.disabled,true);assert.equal(posts,0);
 state='enriching';await context.loadTMDBCategoryState();assert.equal(button.disabled,true);
 state='ready';await context.loadTMDBCategoryState();assert.equal(button.disabled,false);
 const getsBeforeSuccess=gets;await button.click();assert.equal(posts,1);assert.equal(drafts,1);assert.equal(gets,getsBeforeSuccess,'successful result must not be immediately overwritten by a GET');assert.equal(nodes[2].textContent,'scanned');
 failPost=true;const getsBeforeError=gets;await button.click();assert.equal(posts,2);assert.equal(gets,getsBeforeError,'error must remain visible before the scheduled refresh');assert.equal(nodes[2].textContent,'timezone problem');assert.equal(button.disabled,false);
 state='current';const before=timers;await context.loadTMDBCategoryState();assert.ok(timers>before,'completed scans must keep checking for fresh evidence');
 console.log('TMDB category UI: token note, busy state, retained result/error, draft refresh and freshness polling passed');
})().catch(error=>{console.error(error);process.exitCode=1});
